rails課題2 宿泊予約アプリ
taniyan512/Stay-Reserve pull request #1
Opened 2022-05-22 01:50 UTC by taniyan512

課題2の作成が完成しましたのでレビューのほどよろしくお願いします。

2022-05-22 08:50 UTC, TakuyaChida requested changes
課題のご提出ありがとうございます！
内容を確認しました。

ユーザ作成時に不具合が起こってしまったため、
「ユーザ新規登録」時の動作確認しかできませんでした。
内容は下記です。
「ユーザ名」を空の状態で「新規登録」ボタンを押下したところ、
ユーザが登録できてしまい、その影響かは未確認ですが登録後のトップページ画面で
メニューが開けない事象となってしまいました。
![スクリーンショット 2022-05-22 17 47 05](https://user-images.githubusercontent.com/74874584/169686569-e6761673-b8cf-46f8-b9db-78d0f6167888.png)

こちら不具合の解消と、新規登録時のバリデーション設定が必要です。
必須であれば、空では登録できないようにする必要性があると思います！
お手数ですがご確認いただき、再度提出をお願いいたします！

2022-05-22 08:50 UTC, TakuyaChida commented on config/routes.rb
> +  get '/' => "home#top"
localhost:3000からTOPに飛ぶように設定できており素晴らしいです！

2022-05-22 08:50 UTC, TakuyaChida commented on app/javascript/packs/application.js
> +require('test.js')
test.jsという名前のファイル名は避けましょう。
動作確認のためにローカルで一時的に作成するためにtest.jsとするのは良いと思いますが、
コミットやプッシュ時には適切な名前にできるようにしましょう！

2022-05-22 08:50 UTC, TakuyaChida commented on app/views/users/registrations/new.html.erb
> +  </div>
こちらview側で必須とありますが、
登録できてしまいました。
登録できてしまったことにより、予期しない不具合が再現されてしまっている状態です。
トップ画面からtest.jsのエラーが起きており、アイコンをクリックしても、メニューが表示されず
一連の動作ができない現象が再現されました。

こちらは必須であればバリデーションを作成するか、
空で入力されたとしても不具合が起きない作りにする必要があると思いました。

2022-05-23 02:03 UTC, merged

2022-05-23 02:43 UTC, taniyan512 commented
プルリクエストの仕方これで合っていますでしょうか？
合っていればレビューのほどよろしくお願いします